version: "3"
services:
  app:
    image: victoralmeida92/liferay-challenge:v1.0
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      TYPEORM_CONNECTION: mysql
      TYPEORM_HOST: db
      TYPEORM_PORT: 3306
      TYPEORM_USERNAME: test
      TYPEORM_PASSWORD: test
      TYPEORM_DATABASE: test

  db:
    image: mariadb:5.5
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
